[docker_vms]
authentik        ansible_host=10.30.1.10   proxmox_node=pvelins01n01
notifiarr        ansible_host=10.30.1.12   proxmox_node=pvelins01n01
jellyseerr       ansible_host=10.30.1.103  proxmox_node=pvelins01n01
huntarr          ansible_host=10.30.1.105  proxmox_node=pvelins01n01
bentopdf         ansible_host=10.30.1.106  proxmox_node=pvelins01n01
metube           ansible_host=10.30.1.107  proxmox_node=pvelins01n01
profilarr        ansible_host=10.30.1.114  proxmox_node=pvelins01n01
uptimekuma       ansible_host=10.30.1.115  proxmox_node=pvelins01n01
convertx         ansible_host=10.30.1.118  proxmox_node=pvelins01n01
speedtest        ansible_host=10.30.1.120  proxmox_node=pvelins01n01
cleanuparr       ansible_host=10.30.1.129  proxmox_node=pvelins01n01
semaphore        ansible_host=10.30.1.19   proxmox_node=pvelins01n01
autobrr          ansible_host=10.30.1.108  proxmox_node=pvelins02n01
nginx            ansible_host=10.30.1.116  proxmox_node=pvelins02n01
flaresolver      ansible_host=10.30.1.117  proxmox_node=pvelins02n01
jackett          ansible_host=10.30.1.119  proxmox_node=pvelins02n01
immich           ansible_host=10.30.1.131  proxmox_node=pvelins02n01

[linux_vms]
cloudflare-ddns  ansible_host=10.30.1.109  proxmox_node=pvelins02n01
piholel01n01     ansible_host=10.30.1.121  proxmox_node=pvelins01n01
piholel01n02     ansible_host=10.30.1.122  proxmox_node=pvelins02n01
piholel02n01     ansible_host=10.30.1.124  proxmox_node=pvelins01n01
piholel02n02     ansible_host=10.30.1.125  proxmox_node=pvelins02n01
tailscale01      ansible_host=10.30.1.127  proxmox_node=pvelins01n01
tailscale02      ansible_host=10.30.1.128  proxmox_node=pvelins02n01

[tailscale]
tailscale01      ansible_host=10.30.1.127  proxmox_node=pvelins01n01
tailscale02      ansible_host=10.30.1.128  proxmox_node=pvelins02n01

[proxmox]
pvewins01n01     ansible_host=10.30.1.7
pvewins02n01     ansible_host=10.30.1.8
pvewins03n01     ansible_host=10.30.1.41
pvelins01n01     ansible_host=10.30.1.9
pvelins02n01     ansible_host=10.30.1.14
pvelins03n01     ansible_host=10.30.1.40

[pbs]
pbs01            ansible_host=10.30.1.5

[proxmox:vars]
ansible_port=22
ansible_user=root
ansible_python_interpreter=/usr/bin/python3

[pbs:vars]
ansible_port=22
ansible_user=root
ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_port=2222
ansible_python_interpreter=/usr/bin/python3.12
