[windows_server]
sonarrtv         ansible_host=10.30.1.11   proxmox_node=pvewins01n01
sonarrrobert     ansible_host=10.30.1.17   proxmox_node=pvewins01n01
radarrrobert     ansible_host=10.30.1.18   proxmox_node=pvewins01n01
mailstore01      ansible_host=10.30.1.27   proxmox_node=pvewins01n01
radarrmov        ansible_host=10.30.1.13   proxmox_node=pvewins02n01
jellyfin         ansible_host=10.30.1.15   proxmox_node=pvewins02n01
iis01            ansible_host=10.30.1.16   proxmox_node=pvewins02n01
mailstore02      ansible_host=10.30.1.32   proxmox_node=pvewins02n01
mailstore03      ansible_host=10.30.1.33   proxmox_node=pvewins02n01
mailstore04      ansible_host=10.30.1.34   proxmox_node=pvewins02n01
mailstore05      ansible_host=10.30.1.35   proxmox_node=pvewins02n01
youtubedl        ansible_host=10.30.1.36   proxmox_node=pvewins02n01
btpritv          ansible_host=10.30.1.37   proxmox_node=pvewins03n01
btprimov         ansible_host=10.30.1.38   proxmox_node=pvewins03n01
btpuboth         ansible_host=10.30.1.39   proxmox_node=pvewins03n01

[windows_server:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_scheme=http
